### ISSUE TITLE
Still some dangling references to `p` hanging around

### ISSUE THREAD

**Issue by DOSull** [FoldingSpace/enfolding#24]
There seem to be a few places where method signatures expect to receive `p` which I think is a reference to a processing canvas no longer in use? These make refactoring the code per #5 tricky (and also should be removed as a matter of principle anyway...)

**Comment by nicklally** [comment]
you are correct about 'p' being a remnant from earlier, when we were using p5's instance mode. they should be able to be removed without a problem (i thought i had, but not surprising that i missed a couple). feel free to delete them when you see them!

**Comment by nicklally** [comment]
okay, i think i've deleted all p references in function and methods, so i am closing this issue. thanks for pointing this out
